trigger:
- main

variables:
  subscriptionId: 38ca6696-5c82-4571-b2af-bf3f256cf663
  resourceGroupName: cd5

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Azure ML Studio Workspace and dependencies'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(variables.subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/azureml_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/azureml_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Kafka with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(variables.subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/kafka_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/kafka_infra_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Airbyte with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(variables.subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/airbyte_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airbyte_infra_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy MLflow with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(variables.subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/mlflow_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/mlflow_infra_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Airflow with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(variables.subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/airflow_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airflow_infra_parameters.json'
    deploymentMode: 'Incremental'
