trigger:
- main

variables:
  subscriptionId: '38ca6696-5c82-4571-b2af-bf3f256cf663'
  resourceGroupName: 'test'

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Azure ML Studio Workspace and dependencies'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/azureml_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/azureml_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Kafka with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/kafka_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/kafka_infra_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Airbyte with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/airbyte_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airbyte_infra_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy MLflow with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/mlflow_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/mlflow_infra_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Airflow with its infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/airflow_infra_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airflow_infra_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy VNet Peering between Airbyte and Kafka'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/vnet_peering_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airbyte_kafka_vnet_peering_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy VNet Peering between Kafka and Airflow'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/vnet_peering_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/kafka_airflow_vnet_peering_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy VNet Peering between Airflow and MLflow'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/vnet_peering_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airflow_mlflow_vnet_peering_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Private Endpoint from Airflow to Azure Blob Storage'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/airflow_storage_private_endpoint_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airflow_storage_private_endpoint_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Private Endpoint from Airflow to Azure Blob Storage'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1 ($(subscriptionId))'
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arm_templates/airflow_mlstudio_private_endpoint_template.json'
    csmParametersFile: '$(Build.SourcesDirectory)/arm_templates/airflow_mlstudio_private_endpoint_parameters.json'
    deploymentMode: 'Incremental'
