trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Azure subscription 1 (38ca6696-5c82-4571-b2af-bf3f256cf663)'
      subscriptionId: '38ca6696-5c82-4571-b2af-bf3f256cf663'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'azureml'
      location: 'East US 2'
      csmFile: '$(Build.SourcesDirectory)/_JuliuszB12_LSTM_Attention_redeployment_for_yahoo_stock/azureml_template.json'
      csmParametersFile: '$(Build.SourcesDirectory)/_JuliuszB12_LSTM_Attention_redeployment_for_yahoo_stock/azureml_parameters.json'
      deploymentMode: 'Incremental'
